import { NeuroModule } from "@/app/types";

export const CM_MODULES: NeuroModule[] = [
  {
    id: "cm01",
    code: "CM01",
    name: "Neuroanatomy and Neurophysiology",
    credits: 6,
    kind: "graded",
    countsTowardFinal: true,
    group: "foundations",
    structure: {
      type: "subCourses",
      subCourses: [
        {
          id: "cm01-1",
          name: "Functional Organization of Vertebrate CNS",
          credits: 3,
          graded: false,
          handbookSemester: 1,
        },
        {
          id: "cm01-2",
          name: "Neurophysiology",
          credits: 3,
          graded: true,
          weight: 100,
          handbookSemester: 1,
        },
      ],
    },
  },
  {
    id: "cm02",
    code: "CM02",
    name: "Neural Diseases and Neurogenetics",
    credits: 9,
    kind: "graded",
    countsTowardFinal: true,
    group: "foundations",
    structure: {
      type: "subCourses",
      subCourses: [
        {
          id: "cm02-1",
          name: "Genetic and Molecular Basis of Neural Diseases I",
          credits: 3,
          graded: true,
          weight: 50,
          handbookSemester: 1,
        },
        {
          id: "cm02-2",
          name: "Genetic and Molecular Basis of Neural Diseases II",
          credits: 3,
          graded: true,
          weight: 50,
          handbookSemester: 2,
        },
        {
          id: "cm02-3",
          name: "Human Neurogenetics",
          credits: 3,
          graded: false,
          handbookSemester: 1,
        },
      ],
    },
  },
  {
    id: "cm03",
    code: "CM03",
    name: "Molecular Neurobiology",
    credits: 9,
    kind: "graded",
    countsTowardFinal: true,
    group: "foundations",
    structure: {
      type: "subCourses",
      subCourses: [
        {
          id: "cm03-1",
          name: "Molecular and Cellular Biology of Neurons and Glia",
          credits: 3,
          graded: true,
          weight: 50,
          handbookSemester: 1,
        },
        {
          id: "cm03-2",
          name: "Neurochemistry and Neurotransmitters",
          credits: 3,
          graded: true,
          weight: 50,
          handbookSemester: 2,
        },
        {
          id: "cm03-3",
          name: "Neurohistology and Quantitative Neuromorphology",
          credits: 3,
          graded: false,
          handbookSemester: 2,
        },
      ],
    },
  },
  {
    id: "cm04",
    code: "CM04",
    name: "Sensory Systems",
    credits: 6,
    kind: "graded",
    countsTowardFinal: true,
    group: "foundations",
    structure: {
      type: "subCourses",
      subCourses: [
        {
          id: "cm04-1",
          name: "Sensory Systems 1",
          credits: 3,
          graded: true,
          weight: 50,
          handbookSemester: 1,
        },
        {
          id: "cm04-2",
          name: "Sensory Systems 2",
          credits: 3,
          graded: true,
          weight: 50,
          handbookSemester: 2,
        },
      ],
    },
  },
  {
    id: "cm05",
    code: "CM05",
    name: "Data Analysis",
    credits: 6,
    kind: "graded",
    countsTowardFinal: true,
    group: "foundations",
    structure: {
      type: "guidedSlots",
      slots: [
        {
          id: "cm05-stats",
          label: "Statistics",
          credits: 3,
          graded: true,
          handbookSemester: 1,
          options: [
            { id: "cm05-stats-essential", name: "Essential Statistics" },
            { id: "cm05-stats-advanced", name: "Advanced Statistics" },
          ],
        },
        {
          id: "cm05-math",
          label: "Mathematics / Programming",
          credits: 3,
          graded: false,
          handbookSemester: 2,
          options: [
            { id: "cm05-math-essential", name: "Essential Mathematics" },
            { id: "cm05-math-programming", name: "Basic Programming" },
          ],
        },
      ],
    },
  },
  {
    id: "cm06",
    code: "CM06",
    name: "Advanced Methods",
    credits: 9,
    kind: "graded",
    countsTowardFinal: true,
    group: "advanced",
    hint: "9 CP total required; at least 3 CP graded. Number of courses unrestricted.",
    structure: {
      type: "userAdded",
      targetCredits: 9,
      graded: true,
    },
  },
  {
    id: "cm07",
    code: "CM07",
    name: "Advanced Neuroscience",
    credits: 9,
    kind: "graded",
    countsTowardFinal: true,
    group: "advanced",
    hint: "9 CP total required; at least 3 CP graded. Number of courses unrestricted.",
    structure: {
      type: "userAdded",
      targetCredits: 9,
      graded: true,
    },
  },
  {
    id: "cm08",
    code: "CM08",
    name: "Electives",
    credits: 6,
    kind: "completion",
    countsTowardFinal: false,
    group: "electives",
    structure: {
      type: "userAdded",
      targetCredits: 6,
      graded: false,
    },
  },
  {
    id: "cm09",
    code: "CM09",
    name: "Current Research and RCR",
    credits: 3,
    kind: "completion",
    countsTowardFinal: false,
    group: "research",
    structure: {
      type: "subCourses",
      subCourses: [
        {
          id: "cm09-1",
          name: "Neurocolloquium (Semester 1)",
          credits: 0.5,
          graded: false,
          handbookSemester: 1,
        },
        {
          id: "cm09-1b",
          name: "Neurocolloquium (Semester 2)",
          credits: 0.5,
          graded: false,
          handbookSemester: 2,
        },
        {
          id: "cm09-2",
          name: "Scholarly Research",
          credits: 2,
          graded: false,
          handbookSemester: 3,
        },
      ],
    },
  },
  {
    id: "cm10",
    code: "CM10",
    name: "Laboratory Rotations",
    credits: 27,
    kind: "graded",
    countsTowardFinal: true,
    group: "research",
    structure: {
      type: "subCourses",
      subCourses: [
        {
          id: "cm10-1",
          name: "Laboratory Rotation 1",
          credits: 13,
          graded: true,
          weight: 50,
          handbookSemester: 3,
        },
        {
          id: "cm10-2",
          name: "Laboratory Rotation 2",
          credits: 14,
          graded: true,
          weight: 50,
          handbookSemester: 3,
        },
      ],
    },
  },
  {
    id: "cm11",
    code: "CM11",
    name: "Master's Thesis",
    credits: 30,
    kind: "thesis",
    countsTowardFinal: false,
    group: "thesis",
    structure: {
      type: "subCourses",
      subCourses: [
        {
          id: "cm11-1",
          name: "Master's Thesis",
          credits: 30,
          graded: true,
          weight: 100,
          handbookSemester: 4,
        },
      ],
    },
  },
];
