import { NeuroModule } from "@/app/types";

export const CN_MODULES: NeuroModule[] = [
  {
    id: "cn01",
    code: "CN01",
    name: "Neuroanatomy and Neurophysiology",
    credits: 6,
    kind: "graded",
    countsTowardFinal: true,
    group: "foundations",
    structure: {
      type: "subCourses",
      subCourses: [
        {
          id: "cn01-1",
          name: "Functional Organization of Vertebrate CNS",
          credits: 3,
          graded: false,
          handbookSemester: 1,
        },
        {
          id: "cn01-2",
          name: "Neurophysiology",
          credits: 3,
          graded: true,
          weight: 100,
          handbookSemester: 1,
        },
      ],
    },
  },
  {
    id: "cn02",
    code: "CN02",
    name: "Neural Dynamics",
    credits: 6,
    kind: "graded",
    countsTowardFinal: true,
    group: "foundations",
    structure: {
      type: "subCourses",
      subCourses: [
        {
          id: "cn02-1",
          name: "Lecture",
          credits: 3,
          graded: true,
          weight: 100,
          handbookSemester: 1,
        },
        {
          id: "cn02-2",
          name: "Exercises",
          credits: 3,
          graded: false,
          handbookSemester: 1,
        },
      ],
    },
  },
  {
    id: "cn03",
    code: "CN03",
    name: "Neural Coding",
    credits: 6,
    kind: "graded",
    countsTowardFinal: true,
    group: "foundations",
    structure: {
      type: "subCourses",
      subCourses: [
        {
          id: "cn03-1",
          name: "Lecture",
          credits: 3,
          graded: true,
          weight: 100,
          handbookSemester: 2,
        },
        {
          id: "cn03-2",
          name: "Exercises",
          credits: 3,
          graded: false,
          handbookSemester: 2,
        },
      ],
    },
  },
  {
    id: "cn04",
    code: "CN04",
    name: "Neural Modelling",
    credits: 6,
    kind: "graded",
    countsTowardFinal: true,
    group: "foundations",
    structure: {
      type: "subCourses",
      subCourses: [
        {
          id: "cn04-1",
          name: "Lecture",
          credits: 3,
          graded: true,
          weight: 100,
          handbookSemester: 1,
        },
        {
          id: "cn04-2",
          name: "Exercises",
          credits: 3,
          graded: false,
          handbookSemester: 1,
        },
      ],
    },
  },
  {
    id: "cn05",
    code: "CN05",
    name: "Machine Learning",
    credits: 6,
    kind: "graded",
    countsTowardFinal: true,
    group: "foundations",
    structure: {
      type: "subCourses",
      subCourses: [
        {
          id: "cn05-1",
          name: "Lecture",
          credits: 3,
          graded: true,
          weight: 100,
          handbookSemester: 1,
        },
        {
          id: "cn05-2",
          name: "Exercises",
          credits: 3,
          graded: false,
          handbookSemester: 1,
        },
      ],
    },
  },
  {
    id: "cn06",
    code: "CN06",
    name: "Neural Data Science",
    credits: 6,
    kind: "graded",
    countsTowardFinal: true,
    group: "foundations",
    structure: {
      type: "subCourses",
      subCourses: [
        {
          id: "cn06-1",
          name: "Lecture",
          credits: 3,
          graded: true,
          weight: 50,
          handbookSemester: 2,
        },
        {
          id: "cn06-2",
          name: "Exercises",
          credits: 3,
          graded: true,
          weight: 50,
          handbookSemester: 2,
        },
      ],
    },
  },
  {
    id: "cn07",
    code: "CN07",
    name: "Advanced Computational Neuroscience",
    credits: 9,
    kind: "graded",
    countsTowardFinal: true,
    group: "advanced",
    hint: "9 CP total required; at least 3 CP graded. Number of courses unrestricted.",
    structure: {
      type: "userAdded",
      targetCredits: 9,
      graded: true,
    },
  },
  {
    id: "cn08",
    code: "CN08",
    name: "Advanced Neuroscience",
    credits: 9,
    kind: "graded",
    countsTowardFinal: true,
    group: "advanced",
    hint: "9 CP total required; at least 3 CP graded. Number of courses unrestricted.",
    structure: {
      type: "userAdded",
      targetCredits: 9,
      graded: true,
    },
  },
  {
    id: "cn09",
    code: "CN09",
    name: "Electives",
    credits: 6,
    kind: "completion",
    countsTowardFinal: false,
    group: "electives",
    structure: {
      type: "userAdded",
      targetCredits: 6,
      graded: false,
    },
  },
  {
    id: "cn10",
    code: "CN10",
    name: "Current Research and RCR",
    credits: 3,
    kind: "completion",
    countsTowardFinal: false,
    group: "research",
    structure: {
      type: "subCourses",
      subCourses: [
        {
          id: "cn10-1",
          name: "Neurocolloquium (Semester 1)",
          credits: 0.5,
          graded: false,
          handbookSemester: 1,
        },
        {
          id: "cn10-1b",
          name: "Neurocolloquium (Semester 2)",
          credits: 0.5,
          graded: false,
          handbookSemester: 2,
        },
        {
          id: "cn10-2",
          name: "Scholarly Research",
          credits: 2,
          graded: false,
          handbookSemester: 3,
        },
      ],
    },
  },
  {
    id: "cn11",
    code: "CN11",
    name: "Laboratory Rotations",
    credits: 27,
    kind: "graded",
    countsTowardFinal: true,
    group: "research",
    structure: {
      type: "subCourses",
      subCourses: [
        {
          id: "cn11-1",
          name: "Laboratory or Essay Rotation 1",
          credits: 13,
          graded: true,
          weight: 50,
          handbookSemester: 3,
        },
        {
          id: "cn11-2",
          name: "Laboratory Rotation 2",
          credits: 14,
          graded: true,
          weight: 50,
          handbookSemester: 3,
        },
      ],
    },
  },
  {
    id: "cn12",
    code: "CN12",
    name: "Master's Thesis",
    credits: 30,
    kind: "thesis",
    countsTowardFinal: false,
    group: "thesis",
    structure: {
      type: "subCourses",
      subCourses: [
        {
          id: "cn12-1",
          name: "Master's Thesis",
          credits: 30,
          graded: true,
          weight: 100,
          handbookSemester: 4,
        },
      ],
    },
  },
];
